import sys
import pytest
import os

import z3

curr_dir = os.getcwd()
sys.path.insert(1, os.path.join(curr_dir, "src"))

from src.util.z3_to_java import z3_to_java
from src.jbse.symbol import *
from src.java.type import *

NUM_MODELS = 10

symmap = {
    (("{ROOT}", "mybool"),): JBSESymbolValue(0, JavaTypeBoolean()),
    (("{ROOT}", "mybyte"),): JBSESymbolValue(1, JavaTypeByte()),
    (("{ROOT}", "mychar"),): JBSESymbolValue(2, JavaTypeChar()),
    (("{ROOT}", "myshort"),): JBSESymbolValue(3, JavaTypeShort()),
    (("{ROOT}", "myint"),): JBSESymbolValue(4, JavaTypeInt()),
    (("{ROOT}", "mylong"),): JBSESymbolValue(5, JavaTypeLong()),
    (("{ROOT}", "myfloat"),): JBSESymbolValue(6, JavaTypeFloat()),
    (("{ROOT}", "mydouble"),): JBSESymbolValue(7, JavaTypeDouble()),
}


def test_single_var():
    result = z3_to_java(z3.And(z3.Bool("{V0}")), symmap)
    assert result == "(mybool)"


def test_conjunctive():
    # The following z3 ref is generated by the following JBSE output:
    #     (WIDEN-ID((NARROW-FI((0.3f) + ({V0}))) + (3))) + (WIDEN-ID((NARROW-FI((0.3f) + ({V0}))) + (WIDEN-CI({V1})) + (40))) >= (0.0d)

    # The corresponding Java code is:
    #     (double)((int)(0.3f + x) + (int)(3.0f)) + (double)((int)(0.3f + x) + (int)(c + '(')) >= 0.0d
    # where x: {V0} is a float and c: {V1} is a char.
    result = z3_to_java(
        (
            z3.ToReal(
                z3.BV2Int(
                    (z3.Int2BV(z3.ToInt(z3.RealVal(0.3) + (z3.Real("{V6}"))), 32))
                    + z3.BitVecVal(3, 32),
                    is_signed=True,
                )
            )
        )
        + (
            z3.ToReal(
                z3.BV2Int(
                    (z3.Int2BV(z3.ToInt(z3.RealVal(0.3) + (z3.Real("{V6}"))), 32))
                    + (z3.ZeroExt(16, z3.BitVec("{V2}", 16)))
                    + z3.BitVecVal(40, 32),
                    is_signed=True,
                )
            )
        )
        >= z3.RealVal(0.0),
        symmap,
    )
    # ToReal(If(int2bv(ToInt(3/10 + {V6})) + 3 < 0,
    #       BV2Int(int2bv(ToInt(3/10 + {V6})) + 3) -
    #       4294967296,
    #       BV2Int(int2bv(ToInt(3/10 + {V6})) + 3))) +
    # ToReal(If(int2bv(ToInt(3/10 + {V6})) +
    #         ZeroExt(16, {V2}) +
    #         40 <
    #         0,
    #         BV2Int(int2bv(ToInt(3/10 + {V6})) +
    #                 ZeroExt(16, {V2}) +
    #                 40) -
    #         4294967296,
    #         BV2Int(int2bv(ToInt(3/10 + {V6})) +
    #                 ZeroExt(16, {V2}) +
    #                 40))
    print(result)
    assert False